language: cpp
compiler:
  - clang
  - gcc

branches:
  only:
    - develop
    - testing

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt4-dev-tools libqt4-dev libzmq3-dev libzmq3-dbg libqt4-dbg
  - ./test/build_deps.sh

before_script:
  - mkdir build
  - cd build
  - CMAKE_MODULE_PATH=/usr/share/apps/cmake/Modules cmake .. -DCMAKE_BUILD_TYPE=Debug -DLog4Qt_DIR=/usr/share/qt4/mkspecs/cmake/Log4Qt/

script: make Experimental

notifications:
  email:
    - jacky.alcine@thesii.org
  on_success: change
  on_failure: always
