language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug
script: make test
branches:
  only:
   - master
notifications:
  recipients:
   - spchcntrl-dev@thesii.org
  email:
     on_success: change
     on_failure: always
